## Docker compose setup file
## This file will have setup for all the three environments plus a postgres database
version: "3.7"
services:

  db:
    image: postgres:13
    ports:
      - "127.0.0.1:7777:5432"
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - /var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    image: spongeboi/twt_api
    expose:
      - 8000
    links:
      - db
    environment:
      SECRET_KEY: "${SECRET_KEY}"
      DB_URI: "${DB_URI}"

  nginx:
    image: spongeboi/api_nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - backend
      - db
    volumes:
    - /home/python/API/ssl:/etc/nginx/certs
#network:
# - frontend
# - backend

