version: "3.7"
services:
  postgres:
    image: postgres:13
    ports:
      - "127.0.0.1:7777:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: API
      POSTGRES_PASSWORD: API
      POSTGRES_DB: API

    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      SECRET_KEY: "${SECRET_KEY}"
      DISCORD_CLIENT_ID: "${DISCORD_CLIENT_ID}"
      DISCORD_CLIENT_SECRET: "${DISCORD_CLIENT_SECRET}"
      POSTGRES_URI: postgres://API:API@postgres:5432/API

volumes:
  postgres-data:
