name: Build & Deploy

on:
  release:
    types: [created]

  workflow_run:
    workflows: ["Lint & Test"]
    branches: ["staging"]
    types: ["completed"]

jobs:
  build:
    if: github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push'
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Get branch
        id: branch
        run: |
          if ${{ github.event_name == 'workflow_run' }}; then
            echo "::set-output name=branch::staging"
          else
            echo "::set-output name=branch::main"
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.branch.outputs.branch }}
          submodules: recursive

      - name: Create SHA Container Tag
        id: sha_tag
        run: |
          tag=$(cut -c 1-7 <<< $GITHUB_SHA)
          echo "::set-output name=tag::$tag"

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: Dockerfile
          cache-from: type=registry,ref=ghcr.io/tech-with-tim/api:latest
          cache-to: type=inline
          tags: |
            ghcr.io/tech-with-tim/api:${{ steps.branch.outputs.branch }}-${{ steps.sha_tag.outputs.tag }}
            ghcr.io/tech-with-tim/api:${{ steps.branch.outputs.branch }}-latest
            ghcr.io/tech-with-tim/api:latest
