name: Release - Test, Build & Redeploy

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-18.04
    env:
      REPO: ${{ secrets.DOCKER_REPO_API }}
    steps:
      - uses: actions/checkout@v1
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} 
             -p ${{ secrets.DOCKER_PASS }}
      - name: Build Docker image
	run: docker build . -t $REPO
      - name: Push Docker image
	run: docker push $REPO
  deploy:
    name: Redeploy On Vps
    runs-on: ubuntu-18.04
    needs: [docker]
    env:
      URL: ${{ secrets.DEPLOY_WEBHOOK_URL }}
      TOKEN: ${{secrets.DEPLOY_TOKEN }}
    steps:
      - name: Deploy docker container webhook
	run: curl -X POST -H 'Content-Type: application/json' -d '{"token": "$TOKEN"}' $URL

